name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      # ⚠️ Solução temporária para o bug: adicionando upload-artifact manualmente
      - name: Baixar a ação upload-artifact (workaround)
        uses: actions/upload-artifact@v3

      - name: Executar testes simulados
        run: |
          echo "Nenhum teste implementado ainda. Adicione testes em script.js!"
          echo "Podemos adicionar testes com Jest ou Cypress no futuro."
          echo "Testes simulados aprovados"
          exit 0

      - name: Upload de artefatos para GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: . # ou ./dist, se for esse o diretório gerado

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy para o GitHub Pages
        uses: actions/deploy-pages@v2
