name: Deploy para GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Simular testes
        run: |
          echo "Nenhum teste implementado ainda. Adicione testes em script.js!"
          echo "Testes simulados aprovados."

      - name: Upload de artefatos para GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: . # substitua se necessário (ex: ./dist)

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy para GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2